// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"example-loan.com/loan-app/app/controller"
	"example-loan.com/loan-app/app/repository"
	"example-loan.com/loan-app/app/service"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializeApp() (*Initialization, error) {
	client := ConnectToMongoDB()
	loanRepositoryImpl := repository.LoanRepositoryInit(client)
	loanServiceImpl := service.LoanServiceInit(loanRepositoryImpl)
	loanControllerImpl := controller.LoanControllerInit(loanServiceImpl)
	initialization := Init(loanRepositoryImpl, loanServiceImpl, loanControllerImpl)
	return initialization, nil
}

// injector.go:

var db = wire.NewSet(ConnectToMongoDB)

var repositorySet = wire.NewSet(repository.LoanRepositoryInit, wire.Bind(new(repository.LoanRepository), new(*repository.LoanRepositoryImpl)))

var serviceSet = wire.NewSet(service.LoanServiceInit, wire.Bind(new(service.LoanService), new(*service.LoanServiceImpl)))

var controllerSet = wire.NewSet(controller.LoanControllerInit, wire.Bind(new(controller.LoanController), new(*controller.LoanControllerImpl)))
